services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nestjs:
    build:
      context: ./
    command: npm run start:dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/nestdb
    depends_on:
      - db
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: chris.camacho.dev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: abcd
    volumes:
      - pgadmin-data:/var/lib/pgadmin



volumes:
  pgdata:
  pgadmin-data:
